line:
  channel_access_token: gYH5hA/TLNljDruwBUIdeaNX7CfSX3jyKWxSsTE9mvkk+JJPiEKLPe8abc8UiHkWwUaUVk68dIUoOTUu2Ggkn3N1pCTKbgaat23hJF1WKoMbffq4LXG7VaLJgyCLUMyYu+Hs93xjJ8kHI+AlKFavnQdB04t89/1O/w1cDnyilFU=
  myself_id: Uc13e62e128ee7e80e3a16b98b912710e
  group_id: C58482672c5874ea65b058cb9de5fcebc
