#プランコードとプランを紐づけ

#-----------     ここから特日     -----------
特日:

  - "03807090"  #じゃらんお盆プラン

  - "5917920"   #楽天お盆プラン

  - "G1U"       #るるぶSTお盆プラン
  - "G1V"       #るるぶTWお盆プラン
  - "G1W"       #るるぶ特別室お盆プラン
  - "G1X"       #るるぶ露付お盆プラン
  - "G1Y"       #るるぶ特Bお盆プラン

  - "obon1"     #一休お盆プラン
#-----------     ここまで特日     -----------

#-----------     ここから旬会席     -----------
旬会席:
  - "00786092"  #じゃらんnet
  - "03492383"  #じゃらんnet直前割
  - "03510680"  #じゃらんnet早割30
  - "03532114"  #じゃらんスペシャルウィーク
  - "03554404"  #じゃらんお得な10日間
  - "04379736"  #じゃらんスペシャルウィーク

  - "1559803"   #楽天
  - "5513886"   #楽天直前割
  - "5539995"   #楽天早割30(さき楽28)
  - "5584439"   #楽天スーパーセール旬会席
  - "6057085"   #楽天トラベルサマーセール旬会席

  #るるぶは部屋タイプごとにプランコードが違う
  - "116"       #るるぶ露付き
  - "117"       #るるぶ特別室
  - "118"       #るるぶST
  - "482"       #るるぶTW
  - "A93"       #るるぶ特B
  - "A9R"       #るるぶ露付き
  - "A9S"       #るるぶ特別室
  - "A9T"       #るるぶST
  - "A9U"       #るるぶTW
  - "A9V"       #るるぶ特B
  - "ACR"       #るるぶ直前割
  - "ACX"       #るるぶST早割30
  - "ACY"       #るるぶTW早割30
  - "ACZ"       #るるぶ特別室早割30
  - "AD0"       #るるぶ露付早割30
  - "AD1"       #るるぶ特B早割30
  - "ADJ"       #るるぶ貴賓室
  - "G1Z"       #るるぶSTJapanican
  - "G20"       #るるぶTWJapanican
  - "G21"       #るるぶ特別室Japanican
  - "G22"       #るるぶ露付Japanican
  - "G23"       #るるぶ特BJapanican
  - "G2N"       #るるぶST夏旅タイムセール
  - "G2P"       #るるぶTW夏旅タイムセール
  - "G2R"       #るるぶ露付夏旅タイムセール
  - "G2S"       #るるぶ特B夏旅タイムセール

  - "2017022003"  #一休
  - "akitabi"     #一休冬旅
  - "cyoku"       #一休直前割
  - "haya30"      #一休早割30
  - "sale1"       #一休セールプラン
  - "sale2"       #一休セールプラン

  - "206903312"   #Expedia露付
  - "206903313"   #ExpediaST
  - "206903314"   #Expedia特B
  - "206903315"   #ExpediaTW
  - "207121938"   #Expedia特別室

  - "12807665"    #Agoda

  - "21399505"    #Booking.com

  - "1000112785"  #KNT e宿
  - "1000342019"  #KNT e宿早割30
  - "200000031237" #KNT e宿DP
  - "200000031383" #KNT e宿DP露付・特別室
  - "200000031384" #KNT e宿DPST・特B
  - "200000031385" #KNT e宿DPTW

  - "2001"       #ゆこゆこ

  - "15123457086772" #楽天グローバルプラットフォーム

  - "1477312215" #Trip.com

  - "12917192"   #共通在庫
#-----------     ここまで旬会席     -----------


#-----------     ここからステーキ     -----------
ステーキ:
  - "04413143"  #じゃらんnet
  - "6511757"   #楽天
  - "G0A"       #るるぶST Japanican
  - "G0B"       #るるぶTW Japanican
  - "G0C"       #るるぶ特別室 Japanican
  - "G0D"       #るるぶ露付 Japanican
  - "G0E"       #るるぶ特B Japanican
  - "G24"       #るるぶST
  - "G25"       #るるぶTW
  - "G26"       #るるぶ特別室
  - "G27"       #るるぶ露付
  - "G28"       #るるぶ特B
  - "G29"       #るるぶ貴賓室
  - "DNRST"     #一休
  - "12807599"  #Agoda
  - "21399515"  #Booking.com
  - "1000374674"  #KNT e宿
  - "2003"      #ゆこゆこ
  - "15123457084616" #楽天グローバルプラットフォーム
  - "1478853703" #Trip.com
#-----------     ここまでステーキ     -----------


#-----------     ここから牛すき焼     -----------
牛すき焼:
  - "04413168"  #じゃらんnet
  - "6511791"   #楽天
  - "G2G"       #るるぶST
  - "G2H"       #るるぶTW
  - "G2J"       #るるぶ特別室
  - "G2K"       #るるぶ露付
  - "G2L"       #るるぶ特B
  - "G2M"       #るるぶ貴賓室
  - "DNRSK"     #一休
  - "21399510"  #Booking.com
  - "1000374676"  #KNT e宿
  - "2012"      #ゆこゆこ
  - "1478853664" #Trip.com
#-----------     ここまで牛すき焼     -----------


#-----------     ここから牛しゃぶ     -----------
牛しゃぶ:
  - "04413156"  #じゃらんnet
  - "6511779"   #楽天
  - "G2A"       #るるぶST
  - "G2B"       #るるぶTW
  - "G2C"       #るるぶ特別室
  - "G2D"       #るるぶ露付
  - "G2E"       #るるぶ特B
  - "G2F"       #るるぶ貴賓室
  - "DNRSB"     #一休
  - "21399511"  #Booking.com
  - "1000374675"  #KNT e宿
  - "2011"      #ゆこゆこ
  - "1478853684" #Trip.com
#-----------     ここまで牛しゃぶ     -----------


#-----------     ここからことぶき会席     -----------
ことぶき会席:
  - "01205143"  #じゃらんnet
  - "3283106"   #楽天
  - "722"       #るるぶST
  - "723"       #るるぶTW
  - "725"       #るるぶ露付
  - "A94"       #るるぶ特B
  - "AA0"       #るるぶST
  - "AA1"       #るるぶTW
  - "AA2"       #るるぶ露付
  - "AA3"       #るるぶ特B
  - "ADL"       #るるぶ特別室
  - "ADM"       #るるぶ特別室
  - "ADN"       #るるぶ貴賓室
  - "G05"       #るるぶSTインバウンド
  - "G06"       #るるぶTWインバウンド
  - "G07"       #るるぶ特別室インバウンド
  - "G08"       #るるぶ露付インバウンド
  - "G09"       #るるぶ特Bインバウンド
  - "2017022101"  #一休
  - "12807735"    #Agoda
  - "1000037238"  #KNT e宿
  - "200000031261" #KNT e宿DP
  - "2005"      #ゆこゆこ
  - "15123457086820" #楽天グローバルプラットフォーム
#-----------     ここまでことぶき会席     -----------


#-----------     ここから豚しゃぶ     -----------
豚しゃぶ:
  - "01252231"  #じゃらんnet
  - "4012964"   #楽天
  - "A0S"       #るるぶST
  - "A0T"       #るるぶTW
  - "A0V"       #るるぶ露付
  - "A92"       #るるぶ特B
  - "AAA"       #るるぶST
  - "AAB"       #るるぶTW
  - "AAC"       #るるぶ露付
  - "AAD"       #るるぶ特B
  - "2017022002"  #一休
  - "12807701"    #Agoda
  - "1000075344"  #KNT e宿
  - "200000004456" #KNT e宿DP
  - "15123457086822" #楽天グローバルプラットフォーム
  - "1478853633" #Trip.com
#-----------     ここまで豚しゃぶ     -----------


#-----------     ここから早割60     -----------
早割60:
  - "02540417"  #じゃらんnet
  - "4316992"   #楽天
  - "A96"       #るるぶST早割60
  - "A97"       #るるぶTW早割60
  - "A98"       #るるぶ露付早割60
  - "A99"       #るるぶ特B早割60
  - "2017072702"  #一休
  - "15123457000465"  #楽天グローバルプラットフォーム早割60
#-----------     ここまで早割60     -----------


#-----------     ここから1泊朝食     -----------
1泊朝食:
  - "04053053"  #じゃらん直前割朝食付き
  - "6244439"   #楽天直前割朝食付き
  - "ADT"       #るるぶST直前割朝食付き
  - "ADU"       #るるぶTW直前割朝食付き
  - "ADV"       #るるぶ特B直前割朝食付き
  - "G0P"       #るるぶSTJapanican朝食付き
  - "G0Q"       #るるぶST直前割朝食付き
  - "KZ255qhBU" #一休直前割朝食付き
  - "15123457000362"  #楽天グローバルプラットフォーム直前割朝食付き
#-----------     ここまで1泊朝食     -----------


#-----------     ここから素泊まり     -----------
素泊まり:
  - "02075276"  #じゃらんnet
  - "04053094"  #じゃらん直前割素泊まり
  - "3669883"   #楽天
  - "6244556"   #楽天直前割素泊まり
  - "ABU"       #るるぶ
  - "ABV"       #るるぶ
  - "G0N"       #るるぶ Japanican
  - "G0R"       #るるぶ直前割 Japanican
  - "2018081901"  #一休
  - "KZ255qi3q"   #一休直前割素泊まり
  - "386431682"   #Expedia
  - "12807546"    #Agoda
  - "21432114"    #Booking.com
  - "200000004461"  #KNT e宿DP
  - "2017"      #ゆこゆこ
  - "15123457000361" #楽天グローバルプラットフォーム
  - "15123457827090" #楽天グローバルプラットフォーム
  - "1478820174" #Trip.com
#-----------     ここまで素泊まり     -----------


#-----------     ここから露付個室確約     -----------
露付個室確約:
  - "02854375"  #じゃらんnet
  - "4713657"   #楽天
  - "20220401"  #一休
  - "1000112808"  #KNT e宿
  - "200000031245"  #KNT e宿DP
  - "2006"      #ゆこゆこ
  - "15123457084615" #楽天グローバルプラットフォーム
#-----------     ここまで露付個室確約     -----------
