#OTA毎の部屋タイプコードとリンカーン上のマスタ部屋タイプの紐づけ

#----------------     ここから和室12.5畳     ----------------
和室12.5畳:
  - "01"     #JTB

  - "010"    #近ツ

  - "16J106" #日旅

  - "51"     #JR九州

  - "16002"  #西鉄旅行-
  - "16004"
  - "10002"
  - "10003"
  - "16003"
  - "16005"
  - "03001"
  - "16001"  #-西鉄旅行

  - "0043769" #じゃらんnet

  - "j"       #楽天
  - "j4"

  - "A1"      #るるぶトラベル

  - "2017022003"  #一休.com
  - "2026060901"  #一休.com

  - "201382428"   #Expedia

  - "553264568"  #Agoda

  - "130640822"  #Booking.com

  - "22177"   #e宿

  - "2002"    #ゆこゆこ

  - "123457283868"  #楽天グローバルプラットフォーム

  - "482856066"   #Trip.com

  - "2"   #共通在庫
#----------------     ここまで和室12.5畳     ----------------

#----------------     ここから和室12.5畳素泊まり部屋     ----------------
和室12.5畳素泊まり部屋:
  - "0467257" #じゃらんnet

  - "jf4"     #楽天

  - "A3"      #るるぶ

  - "20200714" #一休.com

  - "316625759" #Expedia

  - "586265916" #Agoda

  - "130640829" #Booking.com

  - "76034"     #e宿

  - "2007"     #ゆこゆこ
  - "2008"     #ゆこゆこ

  - "123457283869" #楽天グローバルプラットフォーム

  - "542479839"    # Trip.com
#----------------     ここまで和室12.5畳素泊まり部屋     ----------------

#----------------     ここから和室18畳     ----------------
和室18畳:
  - "05"     #JTB

  - "0463926" #じゃらんnet
  - "0071921" #じゃらんnet

  - "jw6"     #楽天

  - "A6"      #るるぶ
  - "B2"      #るるぶ

  - "2020061901"  #一休.com

  - "201396193"   #Expedia

  - "130640824"   #Booking.com

  - "22402"       #e宿

  - "2005"        #ゆこゆこ

  - "123457283872"  #楽天グローバルプラットフォーム

  - "482856073"   #Trip.com

  - "4"           #共通在庫
#----------------     ここまで和室18畳     ----------------

#----------------     ここから洋室ツイン36㎡     ----------------
洋室ツイン36㎡:
  - "03"     #JTB

  - "0133061" #じゃらんnet

  - "tw"     #楽天

  - "A4"      #るるぶ

  - "2017022002"  #一休.com

  - "201396194"   #Expedia

  - "553265806"   #Agoda

  - "130640821"   #Booking.com

  - "22405"       #e宿

  - "2003"        #ゆこゆこ

  - "123457283873"  #楽天グローバルプラットフォーム

  - "482856082"   #Trip.com

  - "1"           #共通在庫
#----------------     ここまで洋室ツイン36㎡     ----------------

#----------------     ここから露天風呂付和室12.5畳     ----------------
露天風呂付和室12.5畳:
  - "07"      #JTB

  - "020"     #近ツ

  - "0063627" #じゃらんnet

  - "jrt"     #楽天
  - "jrt4"

  - "A8"      #るるぶ

  - "2017022001"  #一休.com
  - "2026060902"  #一休.com

  - "201396197"   #Expedia

  - "553266771"   #Agoda

  - "130640823"   #Booking.com

  - "22403"       #e宿

  - "2001"        #ゆこゆこ

  - "123457283870"  #楽天グローバルプラットフォーム

  - "482856057"   #Trip.com

  - "3"       #共通在庫
#----------------     ここまで露天風呂付和室12.5畳     ----------------

#----------------     ここから特別室和室10畳+8畳     ----------------
特別室和室10畳+8畳:
  - "04"    #JTB

  - "030"   #近ツ

  - "0071926"  #じゃらんnet

  - "jspn"  #楽天

  - "A5"    #るるぶ

  - "20200601"  #一休.com

  - "201435201" #Expedia

  - "553267710" #Agoda

  - "130640825" #Booking.com

  - "22404"     #e宿

  - "123457283871"  #楽天グローバルプラットフォーム

  - "482856092" #Trip.com
#----------------     ここから特別室和室10畳+8畳     ----------------

#----------------     ここから貴賓室     ----------------
貴賓室:
  - "0202056"   #じゃらんnet

  - "kihin"     #楽天

  - "B4"        #るるぶ

  - "kihin"     #一休
#----------------     ここまで貴賓室     ----------------

#----------------     ここから洋室シングル     ----------------
洋室シングル:
  - "0234144"   #じゃらんnet
#----------------     ここまで洋室シングル     ----------------

#----------------     ここから【直前】和室12.5畳     ----------------
【直前】和室12.5畳:
  - "0525917"   #じゃらんnet

  - "cyoku"     #楽天

  - "B3"        #るるぶ

  - "cyoku1"    #一休.com
#----------------     ここまで【直前】和室12.5畳     ----------------
